In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

data1 = pd.read_excel(r"C:\Users\user\Documents\dlrlab\grades.xls")
data=data1.iloc[0:93,:]

data1

,Surname,First name,Institution,Department,Email address,State,Started on,Completed,Time taken,Grade/20.00,...,Q. 11 /1.00,Q. 12 /1.00,Q. 13 /1.00,Q. 14 /1.00,Q. 15 /1.00,Q. 16 /1.00,Q. 17 /1.00,Q. 18 /1.00,Q. 19 /1.00,Q. 20 /1.00
0,CHAUHAN,RAHUL,NaN,NaN,raulchauhan97@gmail.com,In progress,2018-04-30 11:32:00,-,-,-,...,-,-,-,-,-,-,-,-,-,-
1,KANDEL,JEEVAN,NaN,NaN,jivankandel@gmail.com,Finished,2018-04-30 12:46:00,2018-04-30 13:09:00,23 mins 5 secs,16,...,1,1,1,1,1,0,0,0,1,1
2,Adhikari,Suyog,NaN,NaN,lionelsuyog@gmail.com,Finished,2018-04-30 13:10:00,2018-04-30 13:18:00,8 mins 1 sec,20,...,1,1,1,1,1,1,1,1,1,1
3,ADHIKARI,ANURAG,NaN,NaN,anuragadhikari4@gmail.com,Finished,2018-04-30 13:21:00,2018-04-30 13:35:00,13 mins 12 secs,20,...,1,1,1,1,1,1,1,1,1,1
4,SHRESTHA,SAMYAM,NaN,NaN,samyam_heli@yahoo.com,Finished,2018-04-30 13:28:00,2018-04-30 13:40:00,11 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
5,ADHIKARI,BISHAL,NaN,NaN,beeshal55@gmail.com,Finished,2018-04-30 13:28:00,2018-04-30 13:39:00,10 mins 47 secs,20,...,1,1,1,1,1,1,1,1,1,1
6,TULADHAR,BODHITA,NaN,NaN,bodhita8@gmail.com,Finished,2018-04-30 13:31:00,2018-04-30 13:56:00,24 mins 24 secs,19,...,1,1,1,0,1,1,1,1,1,1
7,SHRESTHA,NEHA,NaN,NaN,neha215shrestha@gmail.com,Finished,2018-04-30 13:34:00,2018-04-30 14:05:00,30 mins 31 secs,20,...,1,1,1,1,1,1,1,1,1,1
8,DUWAL,ABIN,NaN,NaN,aintmea7@gmail.com,Finished,2018-04-30 13:52:00,2018-04-30 14:02:00,10 mins 29 secs,17,...,1,1,0,1,0,1,1,1,1,1
9,POUDEL,RUPESH,NaN,NaN,rupesh.poudel07@gmail.com,Finished,2018-04-30 13:57:00,2018-04-30 14:12:00,14 mins 19 secs,20,...,1,1,1,1,1,1,1,1,1,1
10,GHIMIRE,BISHAL,NaN,NaN,darkgamerbg15@gmail.com,Finished,2018-04-30 14:05:00,2018-04-30 14:14:00,8 mins 53 secs,20,...,1,1,1,1,1,1,1,1,1,1
11,MANANDHAR,SHOAIB,NaN,NaN,shoaibmdr@gmail.com,Finished,2018-04-30 14:09:00,2018-04-30 14:21:00,11 mins 52 secs,20,...,1,1,1,1,1,1,1,1,1,1
12,JHA,BIBHUSAN,NaN,NaN,jha.bibhushan1@gmail.com,Finished,2018-04-30 14:17:00,2018-04-30 14:26:00,8 mins 46 secs,20,...,1,1,1,1,1,1,1,1,1,1
13,SHRESTHA,WATSHALA,NaN,NaN,watshala.shrestha1997@gmail.com,Finished,2018-04-30 14:21:00,2018-04-30 14:37:00,16 mins 37 secs,20,...,1,1,1,1,1,1,1,1,1,1
14,BIKRAM THAPA,BIPUL,NaN,NaN,bipulthapa23@gmail.com,Finished,2018-04-30 14:27:00,2018-04-30 14:45:00,18 mins,20,...,1,1,1,1,1,1,1,1,1,1
15,RAI,RAJSHREE,NaN,NaN,rajshreerai931@gmail.com,Finished,2018-04-30 14:34:00,2018-04-30 14:46:00,11 mins 45 secs,18,...,1,1,0,1,1,1,1,1,1,1
16,SHRESTHA,PALISTHA,NaN,NaN,palludallu91@gmail.com,Finished,2018-04-30 14:35:00,2018-04-30 14:52:00,17 mins 49 secs,20,...,1,1,1,1,1,1,1,1,1,1
17,PAUDYAL,AAKASH,NaN,NaN,aakashpaudyal@gmail.com,Finished,2018-04-30 14:44:00,2018-04-30 15:03:00,18 mins 29 secs,20,...,1,1,1,1,1,1,1,1,1,1
18,OJHA,ANJESH,NaN,NaN,anjeshojha67@gmail.com,Finished,2018-04-30 14:45:00,2018-04-30 14:52:00,6 mins 33 secs,20,...,1,1,1,1,1,1,1,1,1,1
19,PAUDEL,SUJAL,NaN,NaN,thesujal17@gmail.com,Finished,2018-04-30 14:49:00,2018-04-30 15:07:00,17 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
20,CHAUDHARY,BINAYA KUMAR,NaN,NaN,binayachaudari@gmail.com,Finished,2018-04-30 14:58:00,2018-04-30 15:17:00,19 mins 5 secs,19,...,0,1,1,1,1,1,1,1,1,1
21,LACOUL,SUBISH,NaN,NaN,subish9813@gmail.com,Finished,2018-04-30 15:07:00,2018-04-30 15:16:00,8 mins 54 secs,20,...,1,1,1,1,1,1,1,1,1,1
22,BARAL,DIPANKER,NaN,NaN,dipanker1996@gmail.com,Finished,2018-04-30 15:13:00,2018-04-30 15:23:00,9 mins 48 secs,20,...,1,1,1,1,1,1,1,1,1,1
23,ADHIKARI,ANISH,NaN,NaN,microanish@gmail.com,Finished,2018-04-30 15:19:00,2018-04-30 15:35:00,16 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
24,DANGOL,NISHA,NaN,NaN,envisagednsa@gmail.com,Finished,2018-04-30 15:24:00,2018-04-30 15:34:00,10 mins 26 secs,20,...,1,1,1,1,1,1,1,1,1,1
25,KUNWAR,SAROJ,NaN,NaN,sarojkunwar999@gmail.com,Finished,2018-04-30 15:33:00,2018-04-30 15:47:00,13 mins 45 secs,20,...,1,1,1,1,1,1,1,1,1,1
26,CHHETRI,SABIN,NaN,NaN,sabin.j.kzetri@gmail.com,Finished,2018-04-30 15:45:00,2018-04-30 15:53:00,7 mins 56 secs,19,...,1,1,1,1,1,1,1,1,1,1
27,BAIDAR,RASIL,NaN,NaN,rasilgrt@gmail.com,Finished,2018-04-30 17:14:00,2018-04-30 17:32:00,17 mins 46 secs,20,...,1,1,1,1,1,1,1,1,1,1
28,Dahal,Aazad,Kathmandu University,Computer Engineering,aazad.dahal@gmail.com,Finished,2018-04-30 17:44:00,2018-04-30 18:14:00,29 mins 52 secs,18,...,1,1,1,1,1,1,0,1,1,1
29,CHAPAGAIN,ASHUTOSH,NaN,NaN,itsmeashutosh43@gmail.com,Finished,2018-04-30 23:03:00,2018-04-30 23:29:00,25 mins 34 secs,13,...,1,1,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,SHAH,AYUSH KUMAR,NaN,NaN,ayush.kumar.shah@gmail.com,Finished,2018-05-01 05:17:00,2018-05-01 05:27:00,10 mins 6 secs,20,...,1,1,1,1,1,1,1,1,1,1
65,PRAJAPATI,SUNIL,NaN,NaN,sunilpzpt@gmail.com,Finished,2018-05-01 05:55:00,2018-05-01 06:05:00,9 mins 35 secs,20,...,1,1,1,1,1,1,1,1,1,1
66,BHATTA,KUSHAL,NaN,NaN,kushal.bhatta12@gmail.com,Finished,2018-05-01 06:18:00,2018-05-01 06:30:00,12 mins 10 secs,20,...,1,1,1,1,1,1,1,1,1,1
67,MOKTAN LAMA,AYOUSH,NaN,NaN,aayushlama26@gmail.com,Finished,2018-05-01 06:26:00,2018-05-01 06:44:00,18 mins 37 secs,20,...,1,1,1,1,1,1,1,1,1,1
68,SHRESTHA,BIBASH,NaN,NaN,bibashshrestha@gmail.com,Finished,2018-05-01 07:10:00,2018-05-01 07:36:00,25 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
69,PANDEY,BIRAT,NaN,NaN,biratpandey77@gmail.com,Finished,2018-05-01 07:29:00,2018-05-01 07:43:00,14 mins 5 secs,18,...,1,1,1,1,1,1,0,1,1,0
70,GAUTAM,AAKASH,NaN,NaN,aakashgautam106@gmail.com,Finished,2018-05-01 07:45:00,2018-05-01 07:50:00,5 mins 8 secs,20,...,1,1,1,1,1,1,1,1,1,1
71,DAHAL,PRELISA,NaN,NaN,dprelisa@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 08:49:00,1 hour,14,...,1,1,1,1,0,1,1,1,1,0
72,UPRETI,AMIT,NaN,NaN,a.u.aua937@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 07:57:00,8 mins 5 secs,20,...,1,1,1,1,1,1,1,1,1,1
73,NEUPANE,BIBEK,NaN,NaN,vivekneupane11@gmail.com,Finished,2018-05-01 07:52:00,2018-05-01 07:57:00,4 mins 19 secs,20,...,1,1,1,1,1,1,1,1,1,1
74,GYAWALI,ASHISH,NaN,NaN,asis3005@gmail.com,Finished,2018-05-01 08:00:00,2018-05-01 08:12:00,12 mins 22 secs,20,...,1,1,1,1,1,1,1,1,1,1
75,RANABHAT ROBIN,NARSINGH,NaN,NaN,robinnarsingha123@gmail.com,Finished,2018-05-01 08:04:00,2018-05-01 08:16:00,12 mins 13 secs,20,...,1,1,1,1,1,1,1,1,1,1
76,Kunwar,Ojaswi Shamsher,NaN,NaN,ojaswi.kunwar@gmail.com,Finished,2018-05-01 08:23:00,2018-05-01 08:40:00,17 mins 6 secs,20,...,1,1,1,1,1,1,1,1,1,1
77,BIDARI,SAMBAD,NaN,NaN,sambad32bidari@gmail.com,Finished,2018-05-01 08:25:00,2018-05-01 08:30:00,5 mins 14 secs,20,...,1,1,1,1,1,1,1,1,1,1
78,ARYAL,BIRAT,NaN,NaN,birataryal1998@gmail.com,Finished,2018-05-01 08:44:00,2018-05-01 08:55:00,10 mins 36 secs,19,...,1,1,1,1,1,1,1,1,1,1
79,GHARTI MAGAR,DHAN BAHADUR,NaN,NaN,dhan.gharti.9@gmail.com,Finished,2018-05-01 08:58:00,2018-05-01 09:53:00,55 mins 14 secs,20,...,1,1,1,1,1,1,1,1,1,1
80,DHAKAL,SAURAV,NaN,NaN,saurav.dhakal63@gmail.com,Finished,2018-05-01 09:37:00,2018-05-01 09:48:00,11 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
81,KARN,SUPREEYA,NaN,NaN,supreeya786@yahoo.com,Finished,2018-05-01 10:49:00,2018-05-01 11:10:00,21 mins 7 secs,20,...,1,1,1,1,1,1,1,1,1,1
82,NYACHHYON,SUGAN GOPAL,NaN,NaN,sugan.nyachhyon@gmail.com,Finished,2018-05-01 11:03:00,2018-05-01 11:25:00,22 mins 4 secs,20,...,1,1,1,1,1,1,1,1,1,1
83,THAPA,HEL NERSHING,NaN,NaN,helnershingthapa@gmail.com,Finished,2018-05-01 11:28:00,2018-05-01 11:39:00,10 mins 49 secs,20,...,1,1,1,1,1,1,1,1,1,1
84,SEDHAIN,ANUP,NaN,NaN,npsedhain@gmail.com,Finished,2018-05-01 12:01:00,2018-05-01 12:13:00,12 mins 31 secs,17,...,1,1,1,1,1,0,1,1,1,1
85,BASKOTA,AKSHYATA,NaN,NaN,akshyatabskt02@gmail.com,Finished,2018-05-01 12:14:00,2018-05-01 12:23:00,9 mins 21 secs,20,...,1,1,1,1,1,1,1,1,1,1
86,BISTA,DINANK,NaN,NaN,bista.dinank@gmail.com,Finished,2018-05-01 12:21:00,2018-05-01 12:39:00,18 mins 28 secs,20,...,1,1,1,1,1,1,1,1,1,1
87,BARAL,ELINA,NaN,NaN,elina49elu@gmail.com,Finished,2018-05-01 12:24:00,2018-05-01 12:33:00,9 mins 31 secs,20,...,1,1,1,1,1,1,1,1,1,1
88,GAIRE,KRISHNA,NaN,NaN,krishna.zaire@gmail.com,Finished,2018-05-01 12:35:00,2018-05-01 12:49:00,13 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
89,RAI,DIPESH,NaN,NaN,raidipesh78@gmail.com,Finished,2018-05-01 13:12:00,2018-05-01 13:28:00,15 mins 40 secs,20,...,1,1,1,1,1,1,1,1,1,1
90,KUNWAR,KAMALESH,NaN,NaN,kamalesh_kunwar1000@yahoo.com,Finished,2018-05-01 14:11:00,2018-05-01 14:30:00,19 mins 8 secs,20,...,1,1,1,1,1,1,1,1,1,1
91,BADE,ROJAN,NaN,NaN,rojanbade@gmail.com,Finished,2018-05-01 14:37:00,2018-05-01 15:07:00,29 mins 16 secs,20,...,1,1,1,1,1,1,1,1,1,1
92,Shrestha,Abik,NaN,NaN,abik_shrestha@hotmail.com,Finished,2018-05-01 14:52:00,2018-05-01 15:09:00,16 mins 51 secs,19,...,1,1,1,1,1,1,0,1,1,1
93,Overall average,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,18.95,...,0.98,1,0.96,0.98,0.88,0.93,0.87,0.95,0.97,0.92

In [3]:
data

,Surname,First name,Institution,Department,Email address,State,Started on,Completed,Time taken,Grade/20.00,...,Q. 11 /1.00,Q. 12 /1.00,Q. 13 /1.00,Q. 14 /1.00,Q. 15 /1.00,Q. 16 /1.00,Q. 17 /1.00,Q. 18 /1.00,Q. 19 /1.00,Q. 20 /1.00
0,CHAUHAN,RAHUL,NaN,NaN,raulchauhan97@gmail.com,In progress,2018-04-30 11:32:00,-,-,-,...,-,-,-,-,-,-,-,-,-,-
1,KANDEL,JEEVAN,NaN,NaN,jivankandel@gmail.com,Finished,2018-04-30 12:46:00,2018-04-30 13:09:00,23 mins 5 secs,16,...,1,1,1,1,1,0,0,0,1,1
2,Adhikari,Suyog,NaN,NaN,lionelsuyog@gmail.com,Finished,2018-04-30 13:10:00,2018-04-30 13:18:00,8 mins 1 sec,20,...,1,1,1,1,1,1,1,1,1,1
3,ADHIKARI,ANURAG,NaN,NaN,anuragadhikari4@gmail.com,Finished,2018-04-30 13:21:00,2018-04-30 13:35:00,13 mins 12 secs,20,...,1,1,1,1,1,1,1,1,1,1
4,SHRESTHA,SAMYAM,NaN,NaN,samyam_heli@yahoo.com,Finished,2018-04-30 13:28:00,2018-04-30 13:40:00,11 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
5,ADHIKARI,BISHAL,NaN,NaN,beeshal55@gmail.com,Finished,2018-04-30 13:28:00,2018-04-30 13:39:00,10 mins 47 secs,20,...,1,1,1,1,1,1,1,1,1,1
6,TULADHAR,BODHITA,NaN,NaN,bodhita8@gmail.com,Finished,2018-04-30 13:31:00,2018-04-30 13:56:00,24 mins 24 secs,19,...,1,1,1,0,1,1,1,1,1,1
7,SHRESTHA,NEHA,NaN,NaN,neha215shrestha@gmail.com,Finished,2018-04-30 13:34:00,2018-04-30 14:05:00,30 mins 31 secs,20,...,1,1,1,1,1,1,1,1,1,1
8,DUWAL,ABIN,NaN,NaN,aintmea7@gmail.com,Finished,2018-04-30 13:52:00,2018-04-30 14:02:00,10 mins 29 secs,17,...,1,1,0,1,0,1,1,1,1,1
9,POUDEL,RUPESH,NaN,NaN,rupesh.poudel07@gmail.com,Finished,2018-04-30 13:57:00,2018-04-30 14:12:00,14 mins 19 secs,20,...,1,1,1,1,1,1,1,1,1,1
10,GHIMIRE,BISHAL,NaN,NaN,darkgamerbg15@gmail.com,Finished,2018-04-30 14:05:00,2018-04-30 14:14:00,8 mins 53 secs,20,...,1,1,1,1,1,1,1,1,1,1
11,MANANDHAR,SHOAIB,NaN,NaN,shoaibmdr@gmail.com,Finished,2018-04-30 14:09:00,2018-04-30 14:21:00,11 mins 52 secs,20,...,1,1,1,1,1,1,1,1,1,1
12,JHA,BIBHUSAN,NaN,NaN,jha.bibhushan1@gmail.com,Finished,2018-04-30 14:17:00,2018-04-30 14:26:00,8 mins 46 secs,20,...,1,1,1,1,1,1,1,1,1,1
13,SHRESTHA,WATSHALA,NaN,NaN,watshala.shrestha1997@gmail.com,Finished,2018-04-30 14:21:00,2018-04-30 14:37:00,16 mins 37 secs,20,...,1,1,1,1,1,1,1,1,1,1
14,BIKRAM THAPA,BIPUL,NaN,NaN,bipulthapa23@gmail.com,Finished,2018-04-30 14:27:00,2018-04-30 14:45:00,18 mins,20,...,1,1,1,1,1,1,1,1,1,1
15,RAI,RAJSHREE,NaN,NaN,rajshreerai931@gmail.com,Finished,2018-04-30 14:34:00,2018-04-30 14:46:00,11 mins 45 secs,18,...,1,1,0,1,1,1,1,1,1,1
16,SHRESTHA,PALISTHA,NaN,NaN,palludallu91@gmail.com,Finished,2018-04-30 14:35:00,2018-04-30 14:52:00,17 mins 49 secs,20,...,1,1,1,1,1,1,1,1,1,1
17,PAUDYAL,AAKASH,NaN,NaN,aakashpaudyal@gmail.com,Finished,2018-04-30 14:44:00,2018-04-30 15:03:00,18 mins 29 secs,20,...,1,1,1,1,1,1,1,1,1,1
18,OJHA,ANJESH,NaN,NaN,anjeshojha67@gmail.com,Finished,2018-04-30 14:45:00,2018-04-30 14:52:00,6 mins 33 secs,20,...,1,1,1,1,1,1,1,1,1,1
19,PAUDEL,SUJAL,NaN,NaN,thesujal17@gmail.com,Finished,2018-04-30 14:49:00,2018-04-30 15:07:00,17 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
20,CHAUDHARY,BINAYA KUMAR,NaN,NaN,binayachaudari@gmail.com,Finished,2018-04-30 14:58:00,2018-04-30 15:17:00,19 mins 5 secs,19,...,0,1,1,1,1,1,1,1,1,1
21,LACOUL,SUBISH,NaN,NaN,subish9813@gmail.com,Finished,2018-04-30 15:07:00,2018-04-30 15:16:00,8 mins 54 secs,20,...,1,1,1,1,1,1,1,1,1,1
22,BARAL,DIPANKER,NaN,NaN,dipanker1996@gmail.com,Finished,2018-04-30 15:13:00,2018-04-30 15:23:00,9 mins 48 secs,20,...,1,1,1,1,1,1,1,1,1,1
23,ADHIKARI,ANISH,NaN,NaN,microanish@gmail.com,Finished,2018-04-30 15:19:00,2018-04-30 15:35:00,16 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
24,DANGOL,NISHA,NaN,NaN,envisagednsa@gmail.com,Finished,2018-04-30 15:24:00,2018-04-30 15:34:00,10 mins 26 secs,20,...,1,1,1,1,1,1,1,1,1,1
25,KUNWAR,SAROJ,NaN,NaN,sarojkunwar999@gmail.com,Finished,2018-04-30 15:33:00,2018-04-30 15:47:00,13 mins 45 secs,20,...,1,1,1,1,1,1,1,1,1,1
26,CHHETRI,SABIN,NaN,NaN,sabin.j.kzetri@gmail.com,Finished,2018-04-30 15:45:00,2018-04-30 15:53:00,7 mins 56 secs,19,...,1,1,1,1,1,1,1,1,1,1
27,BAIDAR,RASIL,NaN,NaN,rasilgrt@gmail.com,Finished,2018-04-30 17:14:00,2018-04-30 17:32:00,17 mins 46 secs,20,...,1,1,1,1,1,1,1,1,1,1
28,Dahal,Aazad,Kathmandu University,Computer Engineering,aazad.dahal@gmail.com,Finished,2018-04-30 17:44:00,2018-04-30 18:14:00,29 mins 52 secs,18,...,1,1,1,1,1,1,0,1,1,1
29,CHAPAGAIN,ASHUTOSH,NaN,NaN,itsmeashutosh43@gmail.com,Finished,2018-04-30 23:03:00,2018-04-30 23:29:00,25 mins 34 secs,13,...,1,1,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,TULADHAR,SACHHYAM RATNA,NaN,NaN,tsachhyam@yahoo.com,Finished,2018-05-01 05:04:00,2018-05-01 05:16:00,11 mins 39 secs,20,...,1,1,1,1,1,1,1,1,1,1
64,SHAH,AYUSH KUMAR,NaN,NaN,ayush.kumar.shah@gmail.com,Finished,2018-05-01 05:17:00,2018-05-01 05:27:00,10 mins 6 secs,20,...,1,1,1,1,1,1,1,1,1,1
65,PRAJAPATI,SUNIL,NaN,NaN,sunilpzpt@gmail.com,Finished,2018-05-01 05:55:00,2018-05-01 06:05:00,9 mins 35 secs,20,...,1,1,1,1,1,1,1,1,1,1
66,BHATTA,KUSHAL,NaN,NaN,kushal.bhatta12@gmail.com,Finished,2018-05-01 06:18:00,2018-05-01 06:30:00,12 mins 10 secs,20,...,1,1,1,1,1,1,1,1,1,1
67,MOKTAN LAMA,AYOUSH,NaN,NaN,aayushlama26@gmail.com,Finished,2018-05-01 06:26:00,2018-05-01 06:44:00,18 mins 37 secs,20,...,1,1,1,1,1,1,1,1,1,1
68,SHRESTHA,BIBASH,NaN,NaN,bibashshrestha@gmail.com,Finished,2018-05-01 07:10:00,2018-05-01 07:36:00,25 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
69,PANDEY,BIRAT,NaN,NaN,biratpandey77@gmail.com,Finished,2018-05-01 07:29:00,2018-05-01 07:43:00,14 mins 5 secs,18,...,1,1,1,1,1,1,0,1,1,0
70,GAUTAM,AAKASH,NaN,NaN,aakashgautam106@gmail.com,Finished,2018-05-01 07:45:00,2018-05-01 07:50:00,5 mins 8 secs,20,...,1,1,1,1,1,1,1,1,1,1
71,DAHAL,PRELISA,NaN,NaN,dprelisa@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 08:49:00,1 hour,14,...,1,1,1,1,0,1,1,1,1,0
72,UPRETI,AMIT,NaN,NaN,a.u.aua937@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 07:57:00,8 mins 5 secs,20,...,1,1,1,1,1,1,1,1,1,1
73,NEUPANE,BIBEK,NaN,NaN,vivekneupane11@gmail.com,Finished,2018-05-01 07:52:00,2018-05-01 07:57:00,4 mins 19 secs,20,...,1,1,1,1,1,1,1,1,1,1
74,GYAWALI,ASHISH,NaN,NaN,asis3005@gmail.com,Finished,2018-05-01 08:00:00,2018-05-01 08:12:00,12 mins 22 secs,20,...,1,1,1,1,1,1,1,1,1,1
75,RANABHAT ROBIN,NARSINGH,NaN,NaN,robinnarsingha123@gmail.com,Finished,2018-05-01 08:04:00,2018-05-01 08:16:00,12 mins 13 secs,20,...,1,1,1,1,1,1,1,1,1,1
76,Kunwar,Ojaswi Shamsher,NaN,NaN,ojaswi.kunwar@gmail.com,Finished,2018-05-01 08:23:00,2018-05-01 08:40:00,17 mins 6 secs,20,...,1,1,1,1,1,1,1,1,1,1
77,BIDARI,SAMBAD,NaN,NaN,sambad32bidari@gmail.com,Finished,2018-05-01 08:25:00,2018-05-01 08:30:00,5 mins 14 secs,20,...,1,1,1,1,1,1,1,1,1,1
78,ARYAL,BIRAT,NaN,NaN,birataryal1998@gmail.com,Finished,2018-05-01 08:44:00,2018-05-01 08:55:00,10 mins 36 secs,19,...,1,1,1,1,1,1,1,1,1,1
79,GHARTI MAGAR,DHAN BAHADUR,NaN,NaN,dhan.gharti.9@gmail.com,Finished,2018-05-01 08:58:00,2018-05-01 09:53:00,55 mins 14 secs,20,...,1,1,1,1,1,1,1,1,1,1
80,DHAKAL,SAURAV,NaN,NaN,saurav.dhakal63@gmail.com,Finished,2018-05-01 09:37:00,2018-05-01 09:48:00,11 mins 32 secs,20,...,1,1,1,1,1,1,1,1,1,1
81,KARN,SUPREEYA,NaN,NaN,supreeya786@yahoo.com,Finished,2018-05-01 10:49:00,2018-05-01 11:10:00,21 mins 7 secs,20,...,1,1,1,1,1,1,1,1,1,1
82,NYACHHYON,SUGAN GOPAL,NaN,NaN,sugan.nyachhyon@gmail.com,Finished,2018-05-01 11:03:00,2018-05-01 11:25:00,22 mins 4 secs,20,...,1,1,1,1,1,1,1,1,1,1
83,THAPA,HEL NERSHING,NaN,NaN,helnershingthapa@gmail.com,Finished,2018-05-01 11:28:00,2018-05-01 11:39:00,10 mins 49 secs,20,...,1,1,1,1,1,1,1,1,1,1
84,SEDHAIN,ANUP,NaN,NaN,npsedhain@gmail.com,Finished,2018-05-01 12:01:00,2018-05-01 12:13:00,12 mins 31 secs,17,...,1,1,1,1,1,0,1,1,1,1
85,BASKOTA,AKSHYATA,NaN,NaN,akshyatabskt02@gmail.com,Finished,2018-05-01 12:14:00,2018-05-01 12:23:00,9 mins 21 secs,20,...,1,1,1,1,1,1,1,1,1,1
86,BISTA,DINANK,NaN,NaN,bista.dinank@gmail.com,Finished,2018-05-01 12:21:00,2018-05-01 12:39:00,18 mins 28 secs,20,...,1,1,1,1,1,1,1,1,1,1
87,BARAL,ELINA,NaN,NaN,elina49elu@gmail.com,Finished,2018-05-01 12:24:00,2018-05-01 12:33:00,9 mins 31 secs,20,...,1,1,1,1,1,1,1,1,1,1
88,GAIRE,KRISHNA,NaN,NaN,krishna.zaire@gmail.com,Finished,2018-05-01 12:35:00,2018-05-01 12:49:00,13 mins 24 secs,20,...,1,1,1,1,1,1,1,1,1,1
89,RAI,DIPESH,NaN,NaN,raidipesh78@gmail.com,Finished,2018-05-01 13:12:00,2018-05-01 13:28:00,15 mins 40 secs,20,...,1,1,1,1,1,1,1,1,1,1
90,KUNWAR,KAMALESH,NaN,NaN,kamalesh_kunwar1000@yahoo.com,Finished,2018-05-01 14:11:00,2018-05-01 14:30:00,19 mins 8 secs,20,...,1,1,1,1,1,1,1,1,1,1
91,BADE,ROJAN,NaN,NaN,rojanbade@gmail.com,Finished,2018-05-01 14:37:00,2018-05-01 15:07:00,29 mins 16 secs,20,...,1,1,1,1,1,1,1,1,1,1
92,Shrestha,Abik,NaN,NaN,abik_shrestha@hotmail.com,Finished,2018-05-01 14:52:00,2018-05-01 15:09:00,16 mins 51 secs,19,...,1,1,1,1,1,1,0,1,1,1

In [4]:

df1 = data['Time taken']
x=np.array(df1)
y=x.astype(str)
y

array(['-', '23 mins 5 secs', '8 mins 1 sec', '13 mins 12 secs',
       '11 mins 24 secs', '10 mins 47 secs', '24 mins 24 secs',
       '30 mins 31 secs', '10 mins 29 secs', '14 mins 19 secs',
       '8 mins 53 secs', '11 mins 52 secs', '8 mins 46 secs',
       '16 mins 37 secs', '18 mins', '11 mins 45 secs', '17 mins 49 secs',
       '18 mins 29 secs', '6 mins 33 secs', '17 mins 32 secs',
       '19 mins 5 secs', '8 mins 54 secs', '9 mins 48 secs',
       '16 mins 24 secs', '10 mins 26 secs', '13 mins 45 secs',
       '7 mins 56 secs', '17 mins 46 secs', '29 mins 52 secs',
       '25 mins 34 secs', '7 mins 25 secs', '1 hour', '19 mins 12 secs',
       '13 mins 38 secs', '19 mins 52 secs', '45 mins 30 secs',
       '12 mins 19 secs', '10 mins 11 secs', '29 mins 23 secs',
       '16 mins 15 secs', '13 mins 5 secs', '8 mins 59 secs',
       '12 mins 48 secs', '14 mins 31 secs', '13 mins 25 secs',
       '9 mins 9 secs', '21 mins 40 secs', '21 mins 39 secs',
       '17 mins 5 secs', '27 mins 34 secs', '11 mins 39 secs',
       '15 mins 30 secs', '12 mins 44 secs', '14 mins 28 secs',
       '10 mins 58 secs', '6 mins 56 secs', '16 mins 19 secs',
       '17 mins 37 secs', '8 mins 4 secs', '25 mins 5 secs',
       '26 mins 23 secs', '10 mins 46 secs', '21 mins 13 secs',
       '11 mins 39 secs', '10 mins 6 secs', '9 mins 35 secs',
       '12 mins 10 secs', '18 mins 37 secs', '25 mins 32 secs',
       '14 mins 5 secs', '5 mins 8 secs', '1 hour', '8 mins 5 secs',
       '4 mins 19 secs', '12 mins 22 secs', '12 mins 13 secs',
       '17 mins 6 secs', '5 mins 14 secs', '10 mins 36 secs',
       '55 mins 14 secs', '11 mins 32 secs', '21 mins 7 secs',
       '22 mins 4 secs', '10 mins 49 secs', '12 mins 31 secs',
       '9 mins 21 secs', '18 mins 28 secs', '9 mins 31 secs',
       '13 mins 24 secs', '15 mins 40 secs', '19 mins 8 secs',
       '29 mins 16 secs', '16 mins 51 secs'],
      dtype='<U15')

In [5]:
y.shape

df2=data['Grade/20.00']
df2
x1=np.array(df2)
x1
#a=x1.astype(int)

array(['-', 16, 20, 20, 20, 20, 19, 20, 17, 20, 20, 20, 20, 20, 20, 18, 20,
       20, 20, 20, 19, 20, 20, 20, 20, 20, 19, 20, 18, 13, 20, 10, 17, 20,
       20, 17, 19, 18, 9, 10, 20, 20, 18, 20, 20, 19, 18, 12, 15, 18, 20,
       20, 20, 20, 20, 20, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 18, 20, 14, 20, 20, 20, 20, 20, 20, 19, 20, 20, 20, 20, 20, 17,
       20, 20, 20, 20, 20, 20, 20, 19], dtype=object)

In [6]:
for i in range(93):
    if y[i]=='-':
        y[i]=0
    if x1[i]=='-':
        x1[i]=0
    
    if (y[i].find('hour') == -1):
        y[i]=y[i][0:2]
    else:
        y[i]=60

In [7]:
y=y.astype(int)
y

array([ 0, 23,  8, 13, 11, 10, 24, 30, 10, 14,  8, 11,  8, 16, 18, 11, 17,
       18,  6, 17, 19,  8,  9, 16, 10, 13,  7, 17, 29, 25,  7, 60, 19, 13,
       19, 45, 12, 10, 29, 16, 13,  8, 12, 14, 13,  9, 21, 21, 17, 27, 11,
       15, 12, 14, 10,  6, 16, 17,  8, 25, 26, 10, 21, 11, 10,  9, 12, 18,
       25, 14,  5, 60,  8,  4, 12, 12, 17,  5, 10, 55, 11, 21, 22, 10, 12,
        9, 18,  9, 13, 15, 19, 29, 16])

In [8]:
for i in range(93):
    if x1[i]>=0 and x1[i]<=10:
        x1[i]='low'
    elif x1[i]>10 and x1[i]<=15:
        x1[i]='medium'
    else:
        x1[i]='high'
        
print(x1)

['low' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'medium'
 'high' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'medium' 'medium' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'medium' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high']

In [9]:
subset=data.iloc[:,:]
subset["Time taken"]=y
subset["Grade/20.00"]=x1

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
data

,Surname,First name,Institution,Department,Email address,State,Started on,Completed,Time taken,Grade/20.00,...,Q. 11 /1.00,Q. 12 /1.00,Q. 13 /1.00,Q. 14 /1.00,Q. 15 /1.00,Q. 16 /1.00,Q. 17 /1.00,Q. 18 /1.00,Q. 19 /1.00,Q. 20 /1.00
0,CHAUHAN,RAHUL,NaN,NaN,raulchauhan97@gmail.com,In progress,2018-04-30 11:32:00,-,0,low,...,-,-,-,-,-,-,-,-,-,-
1,KANDEL,JEEVAN,NaN,NaN,jivankandel@gmail.com,Finished,2018-04-30 12:46:00,2018-04-30 13:09:00,23,high,...,1,1,1,1,1,0,0,0,1,1
2,Adhikari,Suyog,NaN,NaN,lionelsuyog@gmail.com,Finished,2018-04-30 13:10:00,2018-04-30 13:18:00,8,high,...,1,1,1,1,1,1,1,1,1,1
3,ADHIKARI,ANURAG,NaN,NaN,anuragadhikari4@gmail.com,Finished,2018-04-30 13:21:00,2018-04-30 13:35:00,13,high,...,1,1,1,1,1,1,1,1,1,1
4,SHRESTHA,SAMYAM,NaN,NaN,samyam_heli@yahoo.com,Finished,2018-04-30 13:28:00,2018-04-30 13:40:00,11,high,...,1,1,1,1,1,1,1,1,1,1
5,ADHIKARI,BISHAL,NaN,NaN,beeshal55@gmail.com,Finished,2018-04-30 13:28:00,2018-04-30 13:39:00,10,high,...,1,1,1,1,1,1,1,1,1,1
6,TULADHAR,BODHITA,NaN,NaN,bodhita8@gmail.com,Finished,2018-04-30 13:31:00,2018-04-30 13:56:00,24,high,...,1,1,1,0,1,1,1,1,1,1
7,SHRESTHA,NEHA,NaN,NaN,neha215shrestha@gmail.com,Finished,2018-04-30 13:34:00,2018-04-30 14:05:00,30,high,...,1,1,1,1,1,1,1,1,1,1
8,DUWAL,ABIN,NaN,NaN,aintmea7@gmail.com,Finished,2018-04-30 13:52:00,2018-04-30 14:02:00,10,high,...,1,1,0,1,0,1,1,1,1,1
9,POUDEL,RUPESH,NaN,NaN,rupesh.poudel07@gmail.com,Finished,2018-04-30 13:57:00,2018-04-30 14:12:00,14,high,...,1,1,1,1,1,1,1,1,1,1
10,GHIMIRE,BISHAL,NaN,NaN,darkgamerbg15@gmail.com,Finished,2018-04-30 14:05:00,2018-04-30 14:14:00,8,high,...,1,1,1,1,1,1,1,1,1,1
11,MANANDHAR,SHOAIB,NaN,NaN,shoaibmdr@gmail.com,Finished,2018-04-30 14:09:00,2018-04-30 14:21:00,11,high,...,1,1,1,1,1,1,1,1,1,1
12,JHA,BIBHUSAN,NaN,NaN,jha.bibhushan1@gmail.com,Finished,2018-04-30 14:17:00,2018-04-30 14:26:00,8,high,...,1,1,1,1,1,1,1,1,1,1
13,SHRESTHA,WATSHALA,NaN,NaN,watshala.shrestha1997@gmail.com,Finished,2018-04-30 14:21:00,2018-04-30 14:37:00,16,high,...,1,1,1,1,1,1,1,1,1,1
14,BIKRAM THAPA,BIPUL,NaN,NaN,bipulthapa23@gmail.com,Finished,2018-04-30 14:27:00,2018-04-30 14:45:00,18,high,...,1,1,1,1,1,1,1,1,1,1
15,RAI,RAJSHREE,NaN,NaN,rajshreerai931@gmail.com,Finished,2018-04-30 14:34:00,2018-04-30 14:46:00,11,high,...,1,1,0,1,1,1,1,1,1,1
16,SHRESTHA,PALISTHA,NaN,NaN,palludallu91@gmail.com,Finished,2018-04-30 14:35:00,2018-04-30 14:52:00,17,high,...,1,1,1,1,1,1,1,1,1,1
17,PAUDYAL,AAKASH,NaN,NaN,aakashpaudyal@gmail.com,Finished,2018-04-30 14:44:00,2018-04-30 15:03:00,18,high,...,1,1,1,1,1,1,1,1,1,1
18,OJHA,ANJESH,NaN,NaN,anjeshojha67@gmail.com,Finished,2018-04-30 14:45:00,2018-04-30 14:52:00,6,high,...,1,1,1,1,1,1,1,1,1,1
19,PAUDEL,SUJAL,NaN,NaN,thesujal17@gmail.com,Finished,2018-04-30 14:49:00,2018-04-30 15:07:00,17,high,...,1,1,1,1,1,1,1,1,1,1
20,CHAUDHARY,BINAYA KUMAR,NaN,NaN,binayachaudari@gmail.com,Finished,2018-04-30 14:58:00,2018-04-30 15:17:00,19,high,...,0,1,1,1,1,1,1,1,1,1
21,LACOUL,SUBISH,NaN,NaN,subish9813@gmail.com,Finished,2018-04-30 15:07:00,2018-04-30 15:16:00,8,high,...,1,1,1,1,1,1,1,1,1,1
22,BARAL,DIPANKER,NaN,NaN,dipanker1996@gmail.com,Finished,2018-04-30 15:13:00,2018-04-30 15:23:00,9,high,...,1,1,1,1,1,1,1,1,1,1
23,ADHIKARI,ANISH,NaN,NaN,microanish@gmail.com,Finished,2018-04-30 15:19:00,2018-04-30 15:35:00,16,high,...,1,1,1,1,1,1,1,1,1,1
24,DANGOL,NISHA,NaN,NaN,envisagednsa@gmail.com,Finished,2018-04-30 15:24:00,2018-04-30 15:34:00,10,high,...,1,1,1,1,1,1,1,1,1,1
25,KUNWAR,SAROJ,NaN,NaN,sarojkunwar999@gmail.com,Finished,2018-04-30 15:33:00,2018-04-30 15:47:00,13,high,...,1,1,1,1,1,1,1,1,1,1
26,CHHETRI,SABIN,NaN,NaN,sabin.j.kzetri@gmail.com,Finished,2018-04-30 15:45:00,2018-04-30 15:53:00,7,high,...,1,1,1,1,1,1,1,1,1,1
27,BAIDAR,RASIL,NaN,NaN,rasilgrt@gmail.com,Finished,2018-04-30 17:14:00,2018-04-30 17:32:00,17,high,...,1,1,1,1,1,1,1,1,1,1
28,Dahal,Aazad,Kathmandu University,Computer Engineering,aazad.dahal@gmail.com,Finished,2018-04-30 17:44:00,2018-04-30 18:14:00,29,high,...,1,1,1,1,1,1,0,1,1,1
29,CHAPAGAIN,ASHUTOSH,NaN,NaN,itsmeashutosh43@gmail.com,Finished,2018-04-30 23:03:00,2018-04-30 23:29:00,25,medium,...,1,1,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,TULADHAR,SACHHYAM RATNA,NaN,NaN,tsachhyam@yahoo.com,Finished,2018-05-01 05:04:00,2018-05-01 05:16:00,11,high,...,1,1,1,1,1,1,1,1,1,1
64,SHAH,AYUSH KUMAR,NaN,NaN,ayush.kumar.shah@gmail.com,Finished,2018-05-01 05:17:00,2018-05-01 05:27:00,10,high,...,1,1,1,1,1,1,1,1,1,1
65,PRAJAPATI,SUNIL,NaN,NaN,sunilpzpt@gmail.com,Finished,2018-05-01 05:55:00,2018-05-01 06:05:00,9,high,...,1,1,1,1,1,1,1,1,1,1
66,BHATTA,KUSHAL,NaN,NaN,kushal.bhatta12@gmail.com,Finished,2018-05-01 06:18:00,2018-05-01 06:30:00,12,high,...,1,1,1,1,1,1,1,1,1,1
67,MOKTAN LAMA,AYOUSH,NaN,NaN,aayushlama26@gmail.com,Finished,2018-05-01 06:26:00,2018-05-01 06:44:00,18,high,...,1,1,1,1,1,1,1,1,1,1
68,SHRESTHA,BIBASH,NaN,NaN,bibashshrestha@gmail.com,Finished,2018-05-01 07:10:00,2018-05-01 07:36:00,25,high,...,1,1,1,1,1,1,1,1,1,1
69,PANDEY,BIRAT,NaN,NaN,biratpandey77@gmail.com,Finished,2018-05-01 07:29:00,2018-05-01 07:43:00,14,high,...,1,1,1,1,1,1,0,1,1,0
70,GAUTAM,AAKASH,NaN,NaN,aakashgautam106@gmail.com,Finished,2018-05-01 07:45:00,2018-05-01 07:50:00,5,high,...,1,1,1,1,1,1,1,1,1,1
71,DAHAL,PRELISA,NaN,NaN,dprelisa@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 08:49:00,60,medium,...,1,1,1,1,0,1,1,1,1,0
72,UPRETI,AMIT,NaN,NaN,a.u.aua937@gmail.com,Finished,2018-05-01 07:49:00,2018-05-01 07:57:00,8,high,...,1,1,1,1,1,1,1,1,1,1
73,NEUPANE,BIBEK,NaN,NaN,vivekneupane11@gmail.com,Finished,2018-05-01 07:52:00,2018-05-01 07:57:00,4,high,...,1,1,1,1,1,1,1,1,1,1
74,GYAWALI,ASHISH,NaN,NaN,asis3005@gmail.com,Finished,2018-05-01 08:00:00,2018-05-01 08:12:00,12,high,...,1,1,1,1,1,1,1,1,1,1
75,RANABHAT ROBIN,NARSINGH,NaN,NaN,robinnarsingha123@gmail.com,Finished,2018-05-01 08:04:00,2018-05-01 08:16:00,12,high,...,1,1,1,1,1,1,1,1,1,1
76,Kunwar,Ojaswi Shamsher,NaN,NaN,ojaswi.kunwar@gmail.com,Finished,2018-05-01 08:23:00,2018-05-01 08:40:00,17,high,...,1,1,1,1,1,1,1,1,1,1
77,BIDARI,SAMBAD,NaN,NaN,sambad32bidari@gmail.com,Finished,2018-05-01 08:25:00,2018-05-01 08:30:00,5,high,...,1,1,1,1,1,1,1,1,1,1
78,ARYAL,BIRAT,NaN,NaN,birataryal1998@gmail.com,Finished,2018-05-01 08:44:00,2018-05-01 08:55:00,10,high,...,1,1,1,1,1,1,1,1,1,1
79,GHARTI MAGAR,DHAN BAHADUR,NaN,NaN,dhan.gharti.9@gmail.com,Finished,2018-05-01 08:58:00,2018-05-01 09:53:00,55,high,...,1,1,1,1,1,1,1,1,1,1
80,DHAKAL,SAURAV,NaN,NaN,saurav.dhakal63@gmail.com,Finished,2018-05-01 09:37:00,2018-05-01 09:48:00,11,high,...,1,1,1,1,1,1,1,1,1,1
81,KARN,SUPREEYA,NaN,NaN,supreeya786@yahoo.com,Finished,2018-05-01 10:49:00,2018-05-01 11:10:00,21,high,...,1,1,1,1,1,1,1,1,1,1
82,NYACHHYON,SUGAN GOPAL,NaN,NaN,sugan.nyachhyon@gmail.com,Finished,2018-05-01 11:03:00,2018-05-01 11:25:00,22,high,...,1,1,1,1,1,1,1,1,1,1
83,THAPA,HEL NERSHING,NaN,NaN,helnershingthapa@gmail.com,Finished,2018-05-01 11:28:00,2018-05-01 11:39:00,10,high,...,1,1,1,1,1,1,1,1,1,1
84,SEDHAIN,ANUP,NaN,NaN,npsedhain@gmail.com,Finished,2018-05-01 12:01:00,2018-05-01 12:13:00,12,high,...,1,1,1,1,1,0,1,1,1,1
85,BASKOTA,AKSHYATA,NaN,NaN,akshyatabskt02@gmail.com,Finished,2018-05-01 12:14:00,2018-05-01 12:23:00,9,high,...,1,1,1,1,1,1,1,1,1,1
86,BISTA,DINANK,NaN,NaN,bista.dinank@gmail.com,Finished,2018-05-01 12:21:00,2018-05-01 12:39:00,18,high,...,1,1,1,1,1,1,1,1,1,1
87,BARAL,ELINA,NaN,NaN,elina49elu@gmail.com,Finished,2018-05-01 12:24:00,2018-05-01 12:33:00,9,high,...,1,1,1,1,1,1,1,1,1,1
88,GAIRE,KRISHNA,NaN,NaN,krishna.zaire@gmail.com,Finished,2018-05-01 12:35:00,2018-05-01 12:49:00,13,high,...,1,1,1,1,1,1,1,1,1,1
89,RAI,DIPESH,NaN,NaN,raidipesh78@gmail.com,Finished,2018-05-01 13:12:00,2018-05-01 13:28:00,15,high,...,1,1,1,1,1,1,1,1,1,1
90,KUNWAR,KAMALESH,NaN,NaN,kamalesh_kunwar1000@yahoo.com,Finished,2018-05-01 14:11:00,2018-05-01 14:30:00,19,high,...,1,1,1,1,1,1,1,1,1,1
91,BADE,ROJAN,NaN,NaN,rojanbade@gmail.com,Finished,2018-05-01 14:37:00,2018-05-01 15:07:00,29,high,...,1,1,1,1,1,1,1,1,1,1
92,Shrestha,Abik,NaN,NaN,abik_shrestha@hotmail.com,Finished,2018-05-01 14:52:00,2018-05-01 15:09:00,16,high,...,1,1,1,1,1,1,0,1,1,1

In [11]:
from sklearn.cross_validation import train_test_split
a=data['Grade/20.00']
b=data['Time taken']
b=b.reshape(-1, 1)
#a.reshape(-1, 1)

X_train, X_test,y_train, y_test=train_test_split(b,a,random_state=1)
print (X_test.shape)
print (X_train.shape)
print (y_train.shape)
print (y_test.shape)
print(type(X_train))
# and
print(type(y_train))

(24, 1)
(69, 1)
(69,)
(24,)
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>

C:\Users\user\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  after removing the cwd from sys.path.

In [12]:
from sklearn import svm
clf = svm.SVC()
clf.fit(b,a)  
import pickle
s = pickle.dumps(clf)
clf2 = pickle.loads(s)
clf2.predict(b)

array(['low', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'low',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'low',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high'], dtype=object)

In [13]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(b, a)    
clf
print(clf.predict(b))

['low' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high']

In [14]:
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("grade")

'grade.pdf'

In [15]:
dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names='time',  
                         class_names=['high','medium','low'],  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = graphviz.Source(dot_data)  
graph 
graph.render('hci')

'hci.pdf'